version: '3.3'
services:

  frontend:
    build: ../frontend/
    volumes:
      - ../frontend/:/app/result_build/

  foodgram_db:
    image: postgres:13.0-alpine
    volumes:
      - /var/lib/postgresql/data/
    depends_on:
      - frontend
    env_file:
      - ./.env

  backend:
    build: ../foodgram_backend/
    restart: always
    volumes:
      - static_value:/app/backend_static/
      - media_value:/app/backend_media/
    depends_on:
      - foodgram_db
    env_file:
      - ./.env

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ./docs:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/backend_static/
      - media_value:/var/html/backend_media/
    depends_on:
      - backend

volumes:
  postgres_data:
  static_value:
  media_value: